//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

// Represents one line of spoken dialogue.
public class DialogueLine
{
	// The text of the line to be spoken.
	private readonly string lineText;

	// The person to do the speaking.
	private readonly Jobs speaker;

	// Constructor for the DialogueLine.
	public DialogueLine(string lineText, Jobs speaker)
	{
		this.lineText = lineText;
		this.speaker = speaker;
	}

	// Accessor for the person speaking the line.
	public Jobs GetSpeaker()
	{
		return this.speaker;
	}

	public void ReadLine()
	{
		// TODO: make this do something.
	}
}


